### ISSUE TITLE
ModuleNotFoundError: No module named 'gql'

### ISSUE THREAD

**Issue by fr3akazo1d-sec** [MythicAgents/ghostwriter#1]
Hi, 

I have installed the Ghostwriter docker into mythic. 

but the container is always restarting and writing this error in the logs: 

```
Traceback (most recent call last):
  File "/Mythic/main.py", line 4, in <module>
    import ghostwriter
  File "/Mythic/ghostwriter/__init__.py", line 14, in <module>
    module = import_module(f"{__name__}.agent_functions." + Path(x).stem)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Mythic/ghostwriter/agent_functions/project_notes_update.py", line 3, in <module>
    from ghostwriter.GhostwriterRequests import GhostwriterAPI
  File "/Mythic/ghostwriter/GhostwriterRequests/GhostwriterAPI.py", line 2, in <module>
    from ghostwriter.GhostwriterRequests.GhostwriterAPIClasses import *
  File "/Mythic/ghostwriter/GhostwriterRequests/GhostwriterAPIClasses.py", line 7, in <module>
    from gql import Client, gql
ModuleNotFoundError: No module named 'gql'
```

i have installed the gql module over pip. and i am running python version 3.11

how can i resolve this error?

**Comment by its-a-feature** [comment]
Great catch! It was missing from the hosted docker build. I updated it and a new image is being built (https://github.com/MythicAgents/ghostwriter/actions/runs/8437815285). Once that's done, reinstall ghostwriter with `sudo ./mythic-cli install github https://github.com/mythicagents/ghostwriter -f` and you should be good to go

**Comment by fr3akazo1d-sec** [comment]
Thanks for the fast replay. i will test it :)

**Comment by fr3akazo1d-sec** [comment]
> Great catch! It was missing from the hosted docker build. I updated it and a new image is being built (https://github.com/MythicAgents/ghostwriter/actions/runs/8437815285). Once that's done, reinstall ghostwriter with `sudo ./mythic-cli install github https://github.com/mythicagents/ghostwriter -f` and you should be good to go

**Comment by fr3akazo1d-sec** [comment]
Thanks its working now :)
